GET http://localhost:8080/api/v1/categories
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.3.4.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

###

GET http://localhost:8080/api/v1/brands/featured
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.3.4.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

###

GET http://localhost:8080/api/v1/brands
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.3.4.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

###

GET http://localhost:8080/api/v1/brands
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.3.4.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

###

GET http://localhost:8080/api/v1/brands
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.3.4.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

###

POST http://localhost:8080/api/v1/auth/authenticate
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.3.4.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*
content-length: 0

###

POST http://localhost:8080/api/v1/auth/authenticate
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.3.4.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*
content-length: 0

###

GET http://localhost:8080/api/v1/admin/getAll
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.3.4.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

###

GET http://localhost:8080/api/v1/admin/getAll
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.3.4.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

###

GET http://localhost:8080/api/v1/user/profile
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.3.4.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

###

GET http://localhost:8080/api/v1/user/profile
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.3.4.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

###

POST http://localhost:8080/tire-trends/api/auth/login
Content-Type: application/json
Content-Length: 78
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.3.4.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

{
  "username": "sadaruwan.optimous@gmail.com",
  "password": "0771594524dS"
}

###

GET http://localhost:8080/tire-trends/api/users/me
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.3.4.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

###

GET http://localhost:8080/tire-trends/api/users/me
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.3.4.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*

###

POST http://localhost:8080/api/v1/user/register?firstName=x9TDQ7yS&lastName=qiddYToQ&email=rpFBsMbl&phoneNumber=mv_bQpTp&address=gDn6Yg7w&password=f64zr__n&profilePicture=MB929Mm0
User-Agent: IntelliJ HTTP Client/IntelliJ IDEA 2024.3.4.1
Accept-Encoding: br, deflate, gzip, x-gzip
Accept: */*
content-length: 0

<> 2025-03-30T205648.201.json

###

